import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { getPages } from "@/lib/api";
import Nav from "@/components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        <main>{children}</main>
        <footer>
          Copyright © {new Date().getFullYear()} UC Irvine Institute of Transportation Engineers. Powered by Next.js and WordPress.
        </footer>
      </body>
    </html>
  );
}

// export async function generateStaticParams() {
//   const pages = await getPages();
//   return pages.map((page: any) => ({ params: { page: page.slug } }));
// }