import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.scss";
import { getPages } from "@/lib/api";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

const defaultFont = Noto_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={defaultFont.className}>
        <Nav />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}

// export async function generateStaticParams() {
//   const pages = await getPages();
//   return pages.map((page: any) => ({ params: { page: page.slug } }));
// }